name: release @xpr/devcache

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: dependencies
        run: npm clean-install
        working-directory: npm

      - name: verify
        run: npm audit signatures
        working-directory: npm

      - name: build
        working-directory: npm
        run: npm run build

      - name: test
        working-directory: npm
        run: npm test

      - name: release
        run: npx semantic-release
        working-directory: npm
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH }}


name: release @xpr/devcache

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
permissions:
  contents: read # for checkout
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance (npm and jsr)
    steps:
      - name: ‚õµÔ∏ècheckout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ‚òÇÔ∏èsetup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: üîëdependencies
        run: npm ci
      - name: üçìverify
        run: npm audit signatures -w packages/node-client
      - name: üåàbuild
        run: npm run build -w packages/node-client
      - name: ü¶ãrelease
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH }}
